// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'ember-light', 'ember-dark', 'indigo-light', 'indigo-dark', 'berry-light', 'berry-dark', 'mono-light', 'mono-dark']
    }
}

export {}
